services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Password
  server:
    image: wschat:latest
    build:
      context: .
      args:
        port: 8080
        hearbeatTime: 30000
        authCode: ''
        databaseURL: 'postgresql://postgres:password@shiny-telegram-w4q9q47r4qvc9gjw-5432.app.github.dev/mydb?schema=public'
    ports:
      - '8080:8080'
